language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get install -y libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev libsmpeg-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev

install:
  - python setup.py install
script:
  - python setup.py test

addons:
  apt:
    update: true
